apps/ksso/urls.py
"""
KAIST 단일인증서비스 URL 설정.
"""

from django.conf.urls import url

from .views import AgreeView, DisagreeView, LoginView, LogoutView, SignUpView, UserInfoView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup/agree/$', AgreeView.as_view()),
    url(r'^signup/disagree/$', DisagreeView.as_view()),

    url(r'^info/$', UserInfoView.as_view()),
]

apps/ot/urls.py
from django.conf.urls import url

from .views.main import MainView
from .views.club import ClubDetailView, ClubListView
from .views.user import TSizeView, ResultView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^result/$', ResultView.as_view()),
    url(r'^tshirt/$', TSizeView.as_view(), name='t_size'),
    url(r'^club/$', ClubListView.as_view(), name='club_list'),
    url(r'^club/(?P<pk>\d+)/$', ClubDetailView.as_view(), name='club_detail'),
]

kaistusc/kaistusc/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

kaistusc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from apps.board.views import BoardView
from apps.manager.views import ServiceView, MainPageView, ErrorView

from apps.board.router import router

handler400 = ErrorView.as_view(template_name='error/400.jinja', status_code=400)
handler403 = ErrorView.as_view(template_name='error/403.jinja', status_code=403)
handler404 = ErrorView.as_view(template_name='error/404.jinja', status_code=404)
handler500 = ErrorView.as_view(template_name='error/500.jinja', status_code=500)

urlpatterns = [
    # Main page
    url(r'^$', MainPageView.as_view(), name='main'),

    url(r'^api/', include(router.urls)),

    # Basic app redirections
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('apps.ksso.urls', namespace='ksso')),

    # Service redirections
    url(r'^(?P<url>usc/rule)/', include('apps.rule.urls.rule')),
    url(r'^(?P<url>board/[a-z0-9]*[a-z]+[a-z0-9]*)/', include('apps.board.urls')),
    url(r'^revision/', include('apps.rule.urls.revision')),

    # Custom static page
    # For freshmen ot
    url(r'^ot/', include('apps.ot.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# debuging mode in Window

apps/ot/models/club.py
from django.db import models


class Club(models.Model):
    """
    동아리 정보
    """

    class Meta:
        verbose_name = '동아리 정보'
        verbose_name_plural = '동아리 정보(들)'

    def __str__(self):
        return str(self.name)

    name = models.CharField(
        max_length=63,
        verbose_name='동아리 이름',
    )
    pages = models.TextField(
        blank=True,
        verbose_name='동아리 페이스북/유튜브 페이지 주소',
    )
    one_line_intro = models.TextField(
        blank=True,
        verbose_name='동아리 한 줄 소개(메인 화면)',
    )
    intro = models.TextField(
        verbose_name='동아리 소개',
    )
    is_band = models.BooleanField(
        default=False,
        verbose_name='밴드 여부',
    )

    video_url1 = models.CharField(
        blank=True,
        max_length=63,
        verbose_name='동아리 소개 비디오 주소 #1',
    )
    video_url2 = models.CharField(
        blank=True,
        max_length=63,
        verbose_name='동아리 소개 비디오 주소 #2',
    )


class Image(models.Model):
    """
    동아리 홍보 사진
    """
    class Meta:
        verbose_name = '동아리 홍보 사진'
        verbose_name_plural = '동아리 홍보 사진(들)'

    def __str__(self):
        return self.club.name

    club = models.ForeignKey(
        Club,
        related_name='images',
        verbose_name='동아리',
    )
    image = models.FileField(
        null=False,
        upload_to='ot/',
        verbose_name='홍보 사진',
    )
    is_main = models.BooleanField(
        default=False,
        verbose_name='메인 화면에 올라갈 사진인가 (하나만 가능)',
    )

apps/ot/models/user.py
from django.db import models
from django.contrib.auth.models import User

from .club import Club


class Freshman(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, related_name='freshman')
    voted_clubs = models.ManyToManyField(Club, related_name='votes')

    sizes = (
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('2XL', '2XL'),
        ('3XL', '3XL'),
    )
    tsize = models.CharField(null=False, max_length=5, choices=sizes)

    BAND_VOTE_LIMIT = 0
    NON_BAND_VOTE_LIMIT = 5

    def vote_limit_exceeded(self, is_band):
        return self.voted_clubs.filter().count() >= 5

apps/ot/models/vote.py
from django.db import models


class VotePolicy(models.Model):
    """
    투표 시작/종료 시간, 서비스/테스트 여부 등을 코드배포 없이 수정하도록 db에 저장
    """
    is_test = models.BooleanField()
    start = models.DateTimeField()
    end = models.DateTimeField()

apps/ot/forms.py
from django.forms import ModelForm
from .models.user import Freshman


class TSizeForm(ModelForm):
    class Meta:
        model = Freshman
        fields = ("tsize",)

    def __init__(self, *args, **kwargs):
        super(TSizeForm, self).__init__(*args, **kwargs)
        self.fields['tsize'].widget.attrs.update({'class': 'form-control'})

apps/manager/views/base.py
"""
사이트 관리도구 기본 뷰.
"""

import os

from django.contrib.auth.mixins import AccessMixin
from django.http import Http404
from django.views.generic import TemplateView

from apps.ksso.mixins import SignUpRequiredMixin
from apps.manager.constants import *
from apps.manager.models import Category, Service


class PermissionContextMixin(object):
    """
    템플릿에서 서비스 권한상수를 사용할 수 있도록 컨텍스트에 넘기는 믹스인.

    :meth:`get_context_data` 는 GET 요청을 처리할 때 CBV에서 자주 사용되는
    메서드입니다. 이것이 호출될 때 7가지 기본 서비스 권한들을 컨텍스트에
    저장하는 믹스인입니다.
    """

    def get_permission_context(self, context):
        """
        7가지 기본 서비스 권한을 컨텍스트에 추가하는 메서드.
        """
        context['PERM_NONE'] = PERM_NONE
        context['PERM_ACCESS'] = PERM_ACCESS
        context['PERM_READ'] = PERM_READ
        context['PERM_COMMENT'] = PERM_COMMENT
        context['PERM_WRITE'] = PERM_WRITE
        context['PERM_EDIT'] = PERM_EDIT
        context['PERM_DELETE'] = PERM_DELETE
        return context

    def get_context_data(self, **kwargs):
        """
        컨텍스트에 들어갈 데이터를 설정하는 메서드.

        :meth:`super` 메서드를 통해 컨텍스트 데이터를 얻어온 후
        :meth:`get_permission_context` 메서드를 호출하여 기본 서비스 권한을
        추가합니다.
        """
        context = super().get_context_data(**kwargs)
        return self.get_permission_context(context)


class PermissionRequiredServiceMixin(AccessMixin):
    """
    뷰를 요청한 사용자가 서비스에 대한 접속권한이 없는 경우 403 에러를
    발생시키는 믹스인.

    서비스가 존재하는 경우 전역변수 `service` 에 서비스 객체를 저장합니다. 이후
    해당 서비스에 대해 사용자의 이용권한을 테스트하고 권한이 없을 경우 403
    에러를 발생시킵니다. 서비스가 존재하지 않는 경우 404 에러를 발생시킵니다.
    403 에러와 404 에러가 발생하면 핸들러를 통해 커스텀 에러페이지로 이동시킬 수
    있습니다.

    이용권한은 전역변수 `required_exception` 에 저장되며, 기본 값은 접근권한으로
    설정되어 있습니다.
    """

    service_name = None
    required_permission = PERM_ACCESS
    raise_exception = True

    def get_service(self, request, *args, **kwargs):
        """
        사용자 요청으로부터 서비스를 얻어내는 매서드.

        기본적으로 사용자가 요청한 URL에 해당하는 정규표현식 패턴으로부터 전달된
        `url` 파라미터가 있을 경우 이와 일치하는 URL을 갖는 서비스를 반환합니다.
        `url` 파라미터가 전달되지 않은 경우 전역변수 `service_name` 와 같은
        이름을 갖는 서비스를 반환합니다. 서비스명은 한국어 이름으로 갈음합니다.

        위의 두 방식 외 기타 방식으로 서비스가 특정되는 경우 본 메서드를 적절히
        오버라이드 하여 로직을 구현하실 수 있습니다.
        """
        if (kwargs.get('url', None)):
            url = os.path.join('/', kwargs['url'])
            return Service.objects.filter(url=url).first()
        return Service.objects.filter(name_ko=self.service_name).first()

    def has_permission(self, request, *args, **kwargs):
        """
        사용자가 서비스 이용권한이 있는지 여부를 반환하는 메서드.

        :meth:`get_service` 메서드를 통한 서비스 얻어내기가 실패한 경우 404
        에러가 발생합니다. 제대로 서비스를 얻어낸 경우 이를 전역변수 `service`에
        저장합니다.
        """
        service = self.get_service(request, *args, **kwargs)
        if not service:
            raise Http404
        self.service = service
        return service.is_permitted(request.user, self.required_permission)

    def dispatch(self, request, *args, **kwargs):
        """
        권한이 없는 사용자의 요청을 사전차단하는 메서드.
        """
        if not self.has_permission(request, *args, **kwargs):
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class NavigatorMixin(object):
    """
    사이트 네비게이터를 생성하여 컨텍스트에 넘기는 믹스인.

    :meth:`get_context_data` 는 GET 요청을 처리할 때 CBV에서 자주 사용되는
    메서드입니다. 이것이 호출될 때 카테고리와 서비스의 계층구조를 컨텍스트에
    저장하는 믹스인입니다.
    """

    def get_context_data(self, **kwargs):
        """
        컨텍스트에 들어갈 데이터를 설정하는 메서드.

        :meth:`super` 메서드를 통해 컨텍스트 데이터를 얻어온 후 카테고리와
        각각의 카테고리 하위의 사용자 접근 가능 서비스를 얻어 사이트 네비게이터
        데이터를 컨텍스트에 추가합니다.
        """
        context = super().get_context_data(**kwargs)
        context['navigator'] = []
        categories = Category.objects.filter(is_open=True)
        for category in categories:
            context['navigator'].append({
                'category': category,
                'services': Service.objects.filter(
                    category=category).accessible_for(self.request.user),
            })
        return context


class PageView(NavigatorMixin, TemplateView):
    """
    페이지 뷰.

    사용자 권한관리가 필요하지 않는 서비스나 고정 페이지를 출력하는 뷰입니다.
    단순히 `TemplateView` 에 네비게이터를 설정한 것에 지나지 않습니다. 이는
    사이트 기본 레이아웃을 사용하기 위함입니다.

    각각의 페이지 역시 서비스가 될 수 있습니다. 서비스는 어떤 뷰를 사용하냐에
    관계있는 개념이 아니며, `Service` 모델의 객체로 등록되어 데이터베이스에
    저장되면 서비스가 됩니다. 따라서 페이지 뷰를 사용하는 컨텐츠 역시 서비스로
    등록할 수 있습니다.
    """

    pass


class ServiceView(
        SignUpRequiredMixin, PermissionContextMixin,
        PermissionRequiredServiceMixin, PageView):
    """
    기본 서비스 뷰.

    서비스의 각 뷰는 본 뷰를 상속하여 구현합니다. 권한에 따른 이용제한 기능과
    각종 필요한 컨텍스트가 여러 믹스인들에 의해 이미 구현되어 있습니다.

    전역변수 `service_name` 에서 대응되는 서비스명을 지정해줄 수 있습니다.
    URL 패턴 정규표현식에 `url` 파라미터가 존재하지 않는 경우 서비스명을 이곳에
    밝혀주세요.

    전역변수 `required_permission` 에서 뷰의 접근에 필요한 최소 서비스 권한을
    설정할 수 있습니다. 이곳에 설정된 권한이 없는 사용자는 403 에러페이지로
    이동 처리됩니다. 더욱 복잡한 권한처리는 :meth:`has_permission` 메서드를
    오버라이드하여 구현할 수 있습니다.
    """

    def get_context_data(self, **kwargs):
        """
        컨텍스트에 서비스 객체를 전달하는 메서드.
        """
        context = super().get_context_data(**kwargs)
        context['service'] = self.service
        return context

apps/ot/views/club.py
from django.views.generic import ListView, DetailView
from django.http import Http404
from django.shortcuts import redirect

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from ..models.club import Club
from ..util import vote_available


class ClubListView(ListView):
    template_name = 'club_list.html'
    context_object_name = 'clubs'

    def get_queryset(self):
        if 'is_band' in self.request.GET:
            if self.request.GET['is_band'] == '0':
                queryset = Club.objects.filter(is_band=False)
            elif self.request.GET['is_band'] == '1':
                queryset = Club.objects.filter(is_band=True)
            else:
                raise Http404
        else:
            queryset = Club.objects.all()

        sorted_queryset = list()

        for pk in [20, 18, 15, 17, 9, 21, 16, 8, 23, 13, 11, 10, 14]:
            sorted_queryset.append(queryset.get(pk=pk))

        return sorted_queryset

        # return queryset.order_by('?')


class ClubDetailView(DetailView):
    template_name = 'club_detail.html'
    model = Club

    def get_context_data(self, **kwargs):
        context = super(ClubDetailView, self).get_context_data(**kwargs)

        user = self.request.user
        available = vote_available(user)
        context['available'] = available

        if hasattr(user, 'freshman'):
            club = self.object

            # 유저가 이미 해당 동아리에 투표했는지 여부
            context['voted'] = bool(user.freshman.voted_clubs.filter(pk=club.pk))
            # 유저가 해당 동아리 계열(밴드/비밴드) 최대 투표수를 넘었는지 여부
            context['exceeded'] = user.freshman.vote_limit_exceeded(club.is_band)

        return context

    @method_decorator(login_required())
    def post(self, request, *args, **kwargs):
        """
        현재 동아리에 투표
        """
        if vote_available(request.user):
            club = self.get_object()
            freshman = request.user.freshman

            voted = freshman.voted_clubs.filter(pk=club.pk)

            if voted:
                freshman.voted_clubs.remove(club)
                freshman.save()
            elif not freshman.vote_limit_exceeded(club.is_band):
                freshman.voted_clubs.add(club)
                freshman.save()

        return redirect('.')

apps/ot/views/user.py
from django.views.generic import FormView, TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Count

from ..forms import TSizeForm
from ..util import vote_available, is_tester
from ..models.club import Club
from ..models.user import Freshman


@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(vote_available), name='dispatch')
class TSizeView(FormView):
    template_name = 'tsize.html'
    form_class = TSizeForm
    success_url = '/ot/'

    def form_valid(self, form):
        if hasattr(self.request.user, 'freshman'):
            self.request.user.freshman.tsize = form.cleaned_data['tsize']
            self.request.user.freshman.save()
        else:
            freshman = form.save(commit=False)
            freshman.user = self.request.user
            freshman.save()

        return super(TSizeView, self).form_valid(form)

    def get_initial(self):
        initial = super(TSizeView, self).get_initial()

        if hasattr(self.request.user, 'freshman'):
            initial['tsize'] = self.request.user.freshman.tsize

        return initial


@method_decorator(user_passes_test(is_tester), name='dispatch')
class ResultView(TemplateView):
    template_name = 'result.html'

    def get_context_data(self, **kwargs):
        context = super(ResultView, self).get_context_data(**kwargs)

        context['clubs'] = Club.objects.all().annotate(cnt=Count('votes')).order_by('-cnt')
        context['bands'] = Club.objects.filter(is_band=True).annotate(cnt=Count('votes')).order_by('-cnt')
        context['non_bands'] = Club.objects.filter(is_band=False).annotate(cnt=Count('votes')).order_by('-cnt')

        context['cnt_voted'] = Freshman.objects.all().count()

        # Personal T shirts size
        freshmen = Freshman.objects.all()

        size_list = ""
        for freshman in freshmen:
            info = freshman.user.portal_info
            size_list += "<p>%s,%s,%s</p>" % (info.ku_kname, info.ku_std_no, freshman.tsize)
        context['size_list'] = size_list

        return context

apps/ot/templates/base/footer.html
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-xs-24 text-center" style="padding-top: 5px;">
        문제가 있으면 연락주세요<br>
        <span class="text-muted">M. yoonjs0510@kaist.ac.kr T. 010-6641-1621</span>
      </div>
      <div class="col-xs-24 text-center" style="padding-top: 5px;">
        Developed by namsan<br>
        <span class="text-muted">M. namsan@kaist.ac.kr T. 010-2966-2436</span>
      </div>
    </div>
  </div>
</nav>

apps/ot/templates/base/header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href={% url 'main' %}>새터 사전 조사</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 't_size' %}">티셔츠 사이즈 조사</a></li>
        <li><a href="{% url 'club_list' %}">공연 동아리 투표</a></li>
{#        <li class="dropdown">#}
{#          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">#}
{#          공연 동아리 투표<span class="caret"></span>#}
{#          </a>#}
{#          <ul class="dropdown-menu">#}
{#            <li><a href="{% url 'club_list' %}?is_band=1">밴드 동아리 목록</a></li>#}
{#            <li><a href="{% url 'club_list' %}?is_band=0">비밴드동아리 목록</a></li>#}
{#          </ul>#}
{#        </li>#}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text">
        {% if user.is_authenticated %}
        {{ user.portal_info.ku_kname }}
        {% else %}
        GUEST
        {% endif %}
        </p></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'ksso:logout' %}" class="btn btn-default navbar-btn" style="padding-top:5px; padding-bottom:5px">Logout</a></li>
        {% else %}
        <li><a href="{% url 'ksso:login' %}?next={{ request.path }}" class="btn btn-default navbar-btn" style="padding-top:5px; padding-bottom:5px">Login</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

apps/ot/templates/base/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>
  <html class="no-js lt-ie9 lt-ie8 lt-ie7">
<![endif]--><!--[if IE 7]>
  <html class="no-js lt-ie9 lt-ie8">
<![endif]--><!--[if IE 8]>
  <html class="no-js lt-ie9">
<![endif]--><!--[if gt IE 8]><!-->
  <html class="no-js">
<!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
      {% block title %}{% endblock %}
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <link rel="shortcut icon" href="/static/img/ico/favicon.ico">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block stylesheets %}
    {% endblock %}
  </head>
  <body style="margin-bottom: 75px;">
    {% block header %}
      {% include 'base/header.html' %}
    {% endblock %}

    <section id="container" class="container">
      {% block contents %}
      {% endblock %}
    </section>

    {% block footer %}
      {% include 'base/footer.html' %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
    {% block javascripts %}
    {% endblock %}
  </body>
</html>