apps/board/urls.py
"""
게시판 URL 설정.
"""

from django.conf.urls import url

from apps.board.views import (
    BoardView,
    ProductView,ProductDeleteView,
    CommentDeleteView,CommentView,
    PostDeleteView, PostEditView, PostView, PostWriteView, PostVoteView,
    BoardBannerWriteView, BoardBannerEditView, BoardBannerDeleteView
)

url_tab = r'^(?:(?P<tab>[a-z0-9]*[a-z]+[a-z0-9]*)/)?'

urlpatterns = [
    url(url_tab + r'product/$',
        ProductView.as_view()),

    url(url_tab + r'banner/new/$',
        BoardBannerWriteView.as_view()),

    url(url_tab + r'banner/edit/$',
        BoardBannerEditView.as_view()),

    url(url_tab + r'banner/(?P<board_banner_id>[0-9]+)/delete/$',
        BoardBannerDeleteView.as_view()),

    url(url_tab + r'new/$',
        PostWriteView.as_view()),

    url(url_tab + r'$',
        BoardView.as_view()),

    url(url_tab + r'product/(?P<product_id>[0-9]+)/delete/$',
        ProductDeleteView.as_view()),

    url(url_tab + r'(?P<post>[0-9]+)/$',
        PostView.as_view()),

    url(url_tab + r'(?P<post>[0-9]+)/edit/$',
        PostEditView.as_view()),

    url(url_tab + r'(?P<post>[0-9]+)/delete/$',
        PostDeleteView.as_view()),

    url(url_tab + r'(?P<post>[0-9]+)/comment/$',
        CommentView.as_view()),

    url(url_tab + r'(?P<post>[0-9]+)/comment/(?P<comment>[0-9]+)/delete/$',
        CommentDeleteView.as_view()),

    url(url_tab + r'(?P<post>[0-9]+)/vote/(?P<mode>up)/$',
        PostVoteView.as_view()),

    url(url_tab + r'(?P<post>[0-9]+)/vote/(?P<mode>down)/$',
        PostVoteView.as_view()),
]

apps/ksso/urls.py
"""
KAIST 단일인증서비스 URL 설정.
"""

from django.conf.urls import url

from .views import AgreeView, DisagreeView, LoginView, LogoutView, SignUpView, UserInfoView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup/agree/$', AgreeView.as_view()),
    url(r'^signup/disagree/$', DisagreeView.as_view()),

    url(r'^info/$', UserInfoView.as_view()),
]

apps/ot/urls.py
from django.conf.urls import url

from .views.main import MainView
from .views.club import ClubDetailView, ClubListView
from .views.user import TSizeView, ResultView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^result/$', ResultView.as_view()),
    url(r'^tshirt/$', TSizeView.as_view(), name='t_size'),
    url(r'^club/$', ClubListView.as_view(), name='club_list'),
    url(r'^club/(?P<pk>\d+)/$', ClubDetailView.as_view(), name='club_detail'),
]

kaistusc/kaistusc/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

kaistusc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from apps.board.views import BoardView
from apps.manager.views import ServiceView, MainPageView, ErrorView

from apps.board.router import router

handler400 = ErrorView.as_view(template_name='error/400.jinja', status_code=400)
handler403 = ErrorView.as_view(template_name='error/403.jinja', status_code=403)
handler404 = ErrorView.as_view(template_name='error/404.jinja', status_code=404)
handler500 = ErrorView.as_view(template_name='error/500.jinja', status_code=500)

urlpatterns = [
    # Main page
    url(r'^$', MainPageView.as_view(), name='main'),

    url(r'^api/', include(router.urls)),

    # Basic app redirections
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('apps.ksso.urls', namespace='ksso')),

    # Service redirections
    url(r'^(?P<url>usc/rule)/', include('apps.rule.urls.rule')),
    url(r'^(?P<url>board/[a-z0-9]*[a-z]+[a-z0-9]*)/', include('apps.board.urls')),
    url(r'^revision/', include('apps.rule.urls.revision')),

    # Custom static page
    # For freshmen ot
    url(r'^ot/', include('apps.ot.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# debuging mode in Window

apps/board/models.py
"""
게시판 모델.
"""

import os
from datetime import date,datetime
from django.utils import timezone

from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from apps.manager.constants import *
from apps.board.constants import *
from apps.manager.models import BaseService, Service, ServiceManager, TopBanner
from kaistusc.settings import MEDIA_URL

class Board(Service):
    """
    게시판을 구현한 모델.

    :class:`Service` 모델을 상속받아 메인페이지 노출여부를 추가로 저장합니다.
    """

    is_main = models.BooleanField(
        _("메인페이지 노출"),
        default=False)

    objects = ServiceManager()

    BOARD_ROLE_CHOICES = (
        (BOARD_ROLE['DEFAULT'], _('기본')),
        (BOARD_ROLE['PROJECT'], _('사업')),
        (BOARD_ROLE['PLANBOOK'], _('정책자료집')),
        (BOARD_ROLE['DEBATE'], _('논의')),
        (BOARD_ROLE['ARCHIVING'], _('아카이빙')),
        (BOARD_ROLE['WORKHOUR'], _('상근관리')),
        (BOARD_ROLE['SPONSOR'], _('제휴리스트')),
        (BOARD_ROLE['SWIPER'], _('격주보고')),
        (BOARD_ROLE['STORE'], _('상점')),
        (BOARD_ROLE['CONTACT'], _('산하기구')),
    )

    role = models.CharField(
        _("보드 역할"),
        max_length=32,
        choices=BOARD_ROLE_CHOICES, default=BOARD_ROLE['DEFAULT'])

    class Meta:
        verbose_name = _('게시판')
        verbose_name_plural = _('게시판(들)')

    def __str__(self):
        return self.name
    
    def check_role(self, role):
        return self.role == role

class BoardTab(BaseService):
    """
    게시판의 탭을 구현한 모델.

    :class:`Service` 모델을 상속받아 속해있는 보드를 추가로 저장합니다.
    """

    parent_board = models.ForeignKey(
        Board,
        verbose_name=_("탭이 속한 게시판"))

    url = models.CharField(
        _("하위 주소"),
        max_length=32,
        help_text=_("탭을 나타낼 하위 경로만 적어주세요('/'를 포함하면 안됩니다)"))

    #: 커스텀 매니저
    objects = ServiceManager()
        
    class Meta:
        ordering = ['parent_board', 'level']
        verbose_name = _('탭')
        verbose_name_plural = _('탭(들)')

    def __str__(self):
        return self.parent_board.name + "/" + self.name

    def get_absolute_url(self):
        url = '/' + self.parent_board.url.strip('/')+'/'+ self.url.strip('/')
        return url

class PostActivity(models.Model):
    """
    포스트 활동을 구현한 모델.

    사용자가 포스트에 정해진 활동을 행하였다는 정보를 기록하는 모델입니다.
    :class:`User` 모델과 :class:`BasePost` 모델 사이의 중간모델 역할을
    수행합니다.

    포스트 조회나 추천/비추천 등 활동이 있을 수 있습니다. 기본적으로 사용자의
    포스트에 대한 활동은 각 포스트마다 최대 한 번 가능합니다.
    """

    user = models.ForeignKey(
        'auth.User',
        verbose_name=_("유저"),
        null=True)

    ip = models.CharField(
        _("IP 주소"),
        max_length=40)

    post = models.ForeignKey(
        'BasePost',
        verbose_name=_("포스트"))

    ACTIVITY_CHOICES = (
        (ACTIVITY_VIEW, _("조회")),
        (ACTIVITY_VOTE, _("추천/비추천")),
    )
    activity = models.CharField(
        _("활동구분"),
        max_length=4, choices=ACTIVITY_CHOICES)

    def save(self, *args, **kwargs):
        """
        사용자 활동을 저장하는 메서드.

        포스트에 해당 사용자가 같은 활동을 이미 진행한 경우 아무런 처리를 하지
        않습니다. 사용자가 로그인이 되어있지 않은 경우 중복활동 여부는 IP 주소로
        판단합니다.

        본 메서드는 중복활동 여부를 반환합니다. 이 반환값을 통해 추가 로직을
        구현할 수도 있습니다.
        """
        if self.user:
            is_new = not PostActivity.objects.filter(
                user=self.user, post=self.post,
                activity=self.activity).exists()
        else:
            is_new = not PostActivity.objects.filter(
                ip=self.ip, post=self.post, activity=self.activity).exists()
        if is_new:
            super().save(*args, **kwargs)
        return is_new


class Tag(models.Model):
    """
    게시글에 달리는 태그 모델.

    게시판별로 가능한 태그를 생성할 수 있습니다.
    """

    board = models.ForeignKey(
        Board,
        verbose_name=_("게시판"))

    name = models.CharField(
        _("태그명"),
        max_length=32, unique=True)

    abbr = models.CharField(
        _("태그 축약어"),
        max_length=16, unique=True,
        help_text=_("긴 태그명의 경우 태그명 대신 표시할 짧은 축약어입니다."))

    slug = models.CharField(
        _("태그 슬러그"),
        max_length=8, unique=True,
        help_text=_("URL 상 태그를 구분짓는 짧은 지시자입니다."))

    class Meta:
        verbose_name = _('태그')
        verbose_name_plural = _('태그(들)')

    def __str__(self):
        return self.name


class BasePost(models.Model):
    """
    포스트를 정의하는 모델.

    게시글과 댓글 등 포스트에 해당하는 모델은 본 베이스 모델을 상속받아
    구현되었습니다. 본 모델은 강력한 포스트 권한 관리와 사용자 활동 관리
    기능을 제공합니다.
    """

    date = models.DateTimeField(
        _("등록일시"),
        auto_now_add=True)

    author = models.ForeignKey(
        'auth.User',
        verbose_name=_("작성자"),
        null=True)

    content = models.TextField(
        _("내용"))

    is_deleted = models.BooleanField(
        _("삭제글"),
        default=False)

    is_secret = models.BooleanField(
        _("비밀글"),
        default=False)

    involved_users = models.ManyToManyField(
        'auth.User',
        through=PostActivity, related_name='involved_posts',
        verbose_name=_("참여자"))

    vote_up = models.IntegerField(
        _("추천수"),
        default=0)

    vote_down = models.IntegerField(
        _("비추천수"),
        default=0)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-date']
    
    def is_owned_by(self, user):
        """
        주어진 사용자의 포스트인지 확인하는 메서드.
        """
        return self.author == user

    def is_permitted(self, user, permission):
        """
        주어진 사용자의 포스트 이용권한을 확인하는 메서드.

        본 메서드는 게시글, 댓글 등 여러 포스트 상속 모델들의 권한 설정을 손쉽게
        커스터마이징 할 수 있도록 :meth:`pre_permitted` 와
        :meth:`post_permitted` 메서드를 호출합니다. 이들은 기본적으로
        :const:`True` 를 반환하며, 포스트 상속 모델에서 두 메서드를 필요 시
        오버라이드 하는 방식으로 활용 가능합니다.
        """
        if user.is_superuser:
            return True
        if not self.pre_permitted(user, permission):
            return False
        if self.is_deleted:
            return False
        if self.is_owned_by(user):
            return True
        if self.is_secret:
            return False
        return self.post_permitted(user, permission)

    def pre_permitted(self, user, permission):
        """
        포스트 이용권한 확인 이전 필수적으로 있어야 하는 권한을 확인하는 메서드.
        """
        return True

    def post_permitted(self, user, permission):
        """
        포스트 이용권한 확인 후 관련 객체의 이용권한을 확인하는 메서드.
        """
        return True

    def get_activity_count(self, activity):
        """
        특정 활동을 진행한 사용자 총수를 반환하는 메서드.

        """
        return PostActivity.objects.filter(
            post=self, activity=activity).count()

    def get_hits(self):
        """
        조회수를 반환하는 메서드.
        """
        return self.get_activity_count(ACTIVITY_VIEW)

    def assign_activity(self, request, activity):
        """
        포스트에 특정 활동을 등록하는 메서드.

        :class:`PostActivity` 의 :meth:`save` 메서드와 동일합니다.
        """
        return PostActivity(
            user=request.user if request.user.is_authenticated else None,
            ip=request.META['REMOTE_ADDR'],
            post=self,
            activity=activity
        ).save()

    def assign_hits(self, request):
        """
        포스트 조회 활동을 등록하는 메서드.
        """
        self.assign_activity(request, ACTIVITY_VIEW)

    def attached_files(self):
        """
        포스트에 첨부된 첨부파일을 리턴하는 메서드.
        """
        return AttachedFile.objects.filter(post=self)



class Post(BasePost):
    """
    게시글을 구현한 모델.
    """

    board = models.ForeignKey(
        Board,
        verbose_name=_("등록 게시판"))

    board_tab = models.ManyToManyField(
        BoardTab,
        blank=True,
        verbose_name=_("등록 탭"))

    title = models.CharField(
        _("제목"),
        max_length=128)

    tag = models.ForeignKey(
        Tag,
        verbose_name=_("태그"),
        null=True, blank=True)

    is_notice = models.BooleanField(
        _("공지글"),
        default=False)

    class Meta:
        verbose_name = _('포스트')
        verbose_name_plural = _('포스트(들)')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return os.path.join(self.board.get_absolute_url(), str(self.id))
        return self.board.get_absolute_url()+'/'+str(self.id)

    def get_first_tab(self):
        return self.board_tab.all().first()

    def pre_permitted(self, user, permission):
        """
        게시글 권한 확인 이전에 게시판 접근권한을 확인하는 메서드.
        """
        return self.board.is_permitted(user, PERM_ACCESS)

    def post_permitted(self, user, permission):
        """
        게시글 권한 확인 이후에 동일 권한이 게시판에도 있는지 확인하는 메서드.
        """
        return self.board.is_permitted(user, permission)


class Comment(BasePost):
    """
    댓글을 구현한 모델.
    """

    parent_post = models.ForeignKey(
        Post,
        verbose_name=_("상위 포스트"))

    class Meta:
        ordering = ['-date']
        verbose_name = _('댓글')
        verbose_name_plural = _('댓글(들)')

    def __str__(self):
        return _("'%s'의 댓글") % self.parent_post

    def get_absolute_url(self):
        return os.path.join(
            self.parent_post.get_absolute_url(), "comment", str(self.id))

    def pre_permitted(self, user, permission):
        """
        댓글 권한 확인 이전에 게시글 읽기권한을 확인하는 메서드.
        """
        return self.parent_post.is_permitted(user, PERM_READ)

    def post_permitted(self, user, permission):
        """
        댓글 권한 확인 이후에 동일 권한이 게시판에도 있는지 확인하는 메서드.
        """
        return self.parent_post.board.is_permitted(user, permission)

class Banner(BasePost):
    """
    배너를 구현한 모델
    """

    title = models.CharField(
        _("제목"),
        max_length=128)

    url = models.URLField(
        _("링크 URL"),
        blank=True, null=True)

    image = models.ImageField(
        _("이미지"),
        upload_to='banner')

    class Meta:
        verbose_name = _('배너')
        verbose_name_plural = _('배너(들)')

    def __str__(self):
        return self.title

class BannerCarousel(models.Model):
    """
    배너 Carousel을 구현한 모델
    """
    banners = models.ManyToManyField(

apps/board/templates/board/banner.jinja
<a href="{{banner.url}}" target="_blank">
    <img class="banner" src="{{banner.image.url}}" alt="{{banner.image.url}}">
</a>

apps/board/templates/board/banner_carousel.jinja
<div id="banner-carousel-{{bannerCarousel.id}}" class="banner-carousel carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    {% for banner in bannerCarousel.banners.all() %}
    <li data-target="#banner-carousel-{{bannerCarousel.id}}" data-slide-to="{{ loop.index0 }}" {% if loop.index0 == 0 %}class="active"{% endif %}></li>
    {% endfor %}
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    {% for banner in bannerCarousel.banners.all() %}
    <div class="item {% if loop.index0 == 0 %}active{% endif %}">
      {% include 'board/banner.jinja' %}
    </div>
    {% endfor %}
  </div>
</div>

apps/board/templates/board/board.jinja
{% extends 'manager/app_base.jinja' %}

{% from 'board/macros.jinja' import make_tag %}

{% block content %}
<div id="board-header">
  <h1 id="board-title" class="text-center">{{ board.name }}</h1>

  {% if board.tabs %}
  <ul class="nav nav-tabs">
    {% for _tab in board.tabs %}
      <li role="presentation" {% if tab == _tab %}class="active"{% endif %}><a href="{{_tab.get_absolute_url()}}">{{_tab.name}}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  {% include 'board/board_banner.jinja' %}
</div>
{% if board.check_role(BOARD_ROLE['DEBATE']) %}
	{% include 'board/post_list/post_list_debate.jinja' %}
{% elif board.check_role(BOARD_ROLE['PLANBOOK']) %}
	{% include 'board/post/pdf_post.jinja' %}
{% elif board.check_role(BOARD_ROLE['ARCHIVING']) %}
  {% include 'board/post_list/post_list_archiving.jinja' %}
{% elif board.check_role(BOARD_ROLE['WORKHOUR']) %}
	{% include 'board/post/workhour_post.jinja' %}
{% elif board.check_role(BOARD_ROLE['SPONSOR']) %}
	{% include 'board/sponsor_post_list.jinja' %}
{% elif board.check_role(BOARD_ROLE['SWIPER']) %}
  {% include 'board/post/post_swiper.jinja' %}
{% elif board.check_role(BOARD_ROLE['STORE']) %}
  {% include 'board/post_list/product_list.jinja' %}
{% elif board.check_role(BOARD_ROLE['CONTACT']) %}
  {% include 'board/post_list/contact_list.jinja' %}
{% else %}
	{% include 'board/post_list/post_list.jinja' %}
{% endif %}
  
{% endblock %}

apps/board/templates/board/board_banner.jinja
{% if board_banner %}
  <div id="board-banner" class="alert alert-info">
    <a href="{{board_banner.url}}"><b>{{board_banner.text}}</b></a>
    {% if request.user.is_superuser %}
      <div class="pull-right">
        <a class="btn btn-link" href="{{ current_path }}/banner/edit/">{{ _('수정') }}</a>
        <button id="delete-board-banner" class="btn btn-link">{{ _('삭제') }}</button>
      </div>
      {% csrf_token %}
    {% endif %}
  </div>
{% elif request.user.is_superuser %}
  <!-- 보드 배너가 없음을 알리고 추가 버튼 생성-->
  <div id="board-banner" class="alert alert-info">
    <b>{{ _('게시판 배너가 등록되지 않았습니다. 필요할 경우 등록 버튼을 눌러주세요.') }}</b>
    <div class="pull-right">
      <a href="{{ current_path }}/banner/new/">{{ _('등록') }}</a>
    </div>
  </div>
{% endif %}

<div 
  id="delete-board-banner-context" 
  data-current-url="{{ current_path }}"
  data-url="{{ current_path }}/banner/{{board_banner.id}}/delete/"
  data-confirm-msg="{{ _('게시판 배너를 삭제하시겠습니까') }}"
  data-no-banner-msg="{{ _('게시판 배너가 등록되지 않았습니다. 필요할 경우 등록 버튼을 눌러주세요.') }}"
  data-register-text="{{ _('등록') }}"
  >
</div>

apps/board/templates/board/board_banner_form.jinja
{% extends 'manager/app_base.jinja' %}

{% block content %}
<form id="board-banner-form" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-inline">
    <input 
      id="board-banner-text-input" 
      type="text" 
      name="text" 
      class="form-control" 
      placeholder="{{_('배너 텍스트를 입력해주세요')}}" 
      {% if board_banner %}
      value="{{ board_banner.text }}" 
      {% endif %} />
  </div>
  <div class="form-inline">
    <textarea 
      id="board-banner-url-input" 
      type="text" 
      name="url" 
      class="form-control" 
      placeholder="{{_('배너 링크를 입력해주세요')}}"
    >{% if board_banner %}{{ board_banner.url }}{% endif %}</textarea>
  </div>
  {% if tab %}
    <input type="hidden" value="{{tab.id}}" name="board_tab"/>
  {% endif %}
  <button type="submit" class="col-xs-12 btn btn-primary">{{ _('등록') }}</button>
</form>
{% endblock %}

apps/board/templates/board/comment.jinja
{% from 'ksso/macros.jinja' import name %}

<div id="comment-id-{{ comment.id }}" class="comment">
  {% if comment.is_deleted %}
    <div class="comment-content-deleted">{{ _("삭제된 댓글입니다.") }}</div>
  {% else %}
    <div class="comment-header clearfix">
      <div class="pull-left">
        {{ name(comment.author) }}<span class="margin-both">|</span>{{ comment.date.strftime('%Y/%m/%d %H:%M') }}
      </div>
      {% if comment.is_permitted(request.user, PERM_DELETE) %}
      <form action="{{ comment.get_absolute_url() }}/delete/" class="pull-right">{% csrf_token %}
        <i class="comment-remove fa fa-times"></i>
      </form>
      {% endif %}
    </div>
    {%- if comment.is_permitted(request.user, PERM_READ) -%}
      <div class="comment-content">
        {{ comment.content }}
      </div>
      {% if comment.attached_files() %}
        <div id="comment-attached-file">
        {{ _('첨부파일') }}
        <p></p>
        {% for file in comment.attached_files() %}
          <p><a href="{{ file.get_absolute_url() }}">{{ file }} ({{ file.get_file_size()|filesizeformat }})</a></p>
        {% endfor %}
        </div>
      {% endif %}
    {%- endif -%}
  {%- endif -%}
  
</div>

apps/board/templates/board/comment_form.jinja
<form id="comment-form" class="input-group">{% csrf_token %}
	<div id="comment-form-content-wrap">
		<textarea class="form-control custom-control" name="content"></textarea>
	</div>
	{% if board.check_role(BOARD_ROLE['DEBATE']) %}
	<input id="comment-form-file" type="file" name="files">
	{% endif %}
	<span id="btn-comment-form" class="input-group-addon btn btn-primary" type="button">{{ _('등록') }}</span>
</form>

<input type="hidden" id="comment-no-input" value="{{ _('댓글 내용을 입력해주세요.') }}"/>

apps/board/templates/board/comment_list.jinja
<div id="comment-list">
    {% for comment in comments %}
        {% include 'board/comment.jinja' %}
    {% endfor %}
    {% if comments.has_next() %}
        <div id="comment-prev-btn" class="comment">
        <span>{{_('이전 댓글 보기')}}</span>
        </div>
        <input id="comment-next-page-num" type="hidden" value="{{comments.next_page_number()}}"/>
    {% endif %}
</div>

apps/board/templates/board/macros.jinja
{% macro make_tag(board, tag, tab) -%}
{% if tag -%}
<div class="tag-item bg-{{ tag.id % 10 }}" onclick="location.href='{% if tab %}{{ tab.get_absolute_url() }}{% else %}{{ board.get_absolute_url() }}{% endif %}?tag={{ tag.slug }}';">{{ tag.abbr }}</div>
{%- endif %}
{%- endmacro %}

{% macro form_group(field, label=False) -%}
<div class="form-group{% if field.errors %} has-error{% endif %}">
{% if label %}
  <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
{% endif %}
{% for error in field.errors %}
  <label class="control-label" for="{{ field.id_for_label }}">{{ error }}</label>
{% endfor %}
  {{ caller(field) }}
</div>
{%- endmacro %}

{% macro post_title_postfix(post) %}
{% if post.is_secret -%}
  <i class="fa fa-lock"></i>
{% endif %}
{% if post.content_en and post.content_ko %}
  <i class="fa fa-globe"></i>
{% endif %}
{% if post.__class__.__name__ == 'ProjectPost' %}
  {% if post.is_pledge %}
    <i class="fa fa-handshake-o" title="{{_('공약')}}"></i>
  {% endif %}
{% endif %}
{% if post.__class__.__name__ == 'DebatePost' %}
  {% if post.is_commentable() %}
  <span class="debate-state debate-ongoing">{{ _('논의중') }}</span>
  {% elif (post.is_closed or post.is_over_due()) %}
  <span class='debate-state debate-finished'>{{ _('종료') }}</span>
  {% else %}
  <span class='debate-state debate-waiting'>{{ _('청원중') }}</span>
  {%- endif -%}
{% endif %}
{% endmacro %}

apps/board/templates/board/post_list_min.jinja
{% from 'board/macros.jinja' import make_tag, post_title_postfix %}

{% macro post_info_min(post) -%}
  <tr onclick="location.href='{{ post.get_absolute_url() }}';">
    <td class="text-left">
    {%- if post.tag -%}
      <span class="margin-right">{{ make_tag(board, post.tag) }}</span>
    {%- endif -%}
      <span class="post-list-title">
      {%- if post.is_deleted -%}
        {{ _('삭제되었습니다.') }}
      {%- elif post.is_secret -%}
      {% if post.is_permitted(request.user, PERM_READ) -%}
        {{ post.title }}
      {%- else -%}
        {{ _('비밀글입니다.') }}
      {%- endif -%}
      {%- else -%}
        {{ post.title }}
      {%- endif -%}
      {{ post_title_postfix(post)}}
      </span>
    </td>
    <td class="text-right">{{ post.date.strftime('%Y/%-m/%-d') }}</td>
  </tr>
{%- endmacro -%}

<table class="main-board table table-hover">
  <caption class="clearfix">
    <div class="pull-left"><a href="{{ board.get_absolute_url() }}">{{ board.name }}</a></div>
    <button class="pull-right btn btn-sm btn-default" onclick="location.href='{{ board.get_absolute_url() }}';">More</button>
  </caption>
  <tbody>
    {% for post in board.post_set.all()[:5] %}
    {{ post_info_min(post) }}
    {% endfor %}
  </tbody>
</table>